### ISSUE TITLE
Bump validator to fix vulnerability

### ISSUE THREAD

**Issue by monil-panchal** [zulhilmizainuddin/nodejs-traceroute#10]
- [validator](https://github.com/zulhilmizainuddin/nodejs-traceroute/blob/d06023a358434d4db3ceb23a5947c149023b8dd7/package.json#L21) version needs to be bumped for fixing vulnerability. 
- Looks like PR is already open for this but needs to be merged by @zulhilmizainuddin, @ericulevik

**Comment by zulhilmizainuddin** [comment]
Updated validator to latest version and published package 1.2.1 to npmjs
