### ISSUE TITLE
Support for ipv4 only

### ISSUE THREAD

**Issue by alexandrudsc** [zulhilmizainuddin/nodejs-traceroute#3]
Hi @zulhilmizainuddin,

Really nice work, thanks. Both `Traceroute` and  `Tracert` use either ipv4 or ipv6 like said [here in the docs](https://linux.die.net/man/8/traceroute):   
```
By default, the program will try to resolve the name given, and choose the appropriate 
protocol automatically
```  
I would really love to have the option to force the usage of ipv4 when I need to.
What do you think?

**Comment by alexandrudsc** [comment]
here's my pr https://github.com/zulhilmizainuddin/nodejs-traceroute/pull/4. I'm not a javascript developer, if you have any suggestions I'm happy to discuss

**Comment by zulhilmizainuddin** [comment]
I have added the option to force the use of ipv4 and ipv6 in the latest package.
https://www.npmjs.com/package/nodejs-traceroute#force-ipv4-or-ipv6

**Comment by alexandrudsc** [comment]
> 
> 
> I have added the option to force the use of ipv4 and ipv6 in the latest package.
> https://www.npmjs.com/package/nodejs-traceroute#force-ipv4-or-ipv6

Looks fantastic, thanks for taking the time for such an elaborated solution. I'll close my issue

**Comment by garytheduck** [comment]
i like that feature too, thanks
