### ISSUE TITLE
Timeout or Hops max

### ISSUE THREAD

**Issue by Dave-c-Ross** [zulhilmizainuddin/nodejs-traceroute#6]
Hey guys, just wandering if it is possible to add a parameter on .trace function, to provide a ttl_max.

**Comment by vicksiyi** [comment]
You can look this:
traceroute.js
```
class Traceroute extends Process {
    constructor(ipVersion = '', sendwait = 0) {
        const args = ['-q', 1, '-z', sendwait, '-n'];
```
It is possiable to add parmeter on .trace function,ro provide a max_ttl(That's sendwait)

**Comment by vicksiyi** [comment]
> Hey guys, just wandering if it is possible to add a parameter on .trace function, to provide a ttl_max.

You can look this:
traceroute.js
```
class Traceroute extends Process {
    constructor(ipVersion = '', sendwait = 0) {
        const args = ['-q', 1, '-z', sendwait, '-n'];
```
It is possiable to add parmeter on .trace function,ro provide a max_ttl(That's sendwait)

**Comment by Dave-c-Ross** [comment]
Great!
Perfect, thank you @vicksiyi
